title: Ye Yang
description: My Personal Blog
author: Ye Yang
logo: /static/img/avatar.png
github: https://github.com/ictyangye
about: PHD student in ICT of CAS

baseurl: "https://ictyangye.github.io"
url: "https://ictyangye.github.io"

allowsearch: true

disqus_shortname: aboutashu
google_analytics: UA-72862926-1

share:
  twitter_username: \#
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 6
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
