title: John Smith
description: My Personal Blog
author: John Smith
logo: /static/img/avatar.png
github: https://github.com/ictyangye
about: Freelance developer

#baseurl: "https://ictyangye.github.io/hcz-jekyll-blog"
#url: "https://ictyangye.github.io/hcz-jekyll-blog"

baseurl: "https://ictyangye.github.io"
url: "https://ictyangye.github.io"

allowsearch: true

disqus_shortname: aboutashu
google_analytics: UA-72862926-1

share:
  twitter_username: \#
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
