title: Ye YANG
description: My Personal Blog
author: Ye YANG
logo: /static/img/avatar.png
github: https://github.com/ictyangye
about: PHD student in ICT of CAS

baseurl: "https://ictyangye.github.io"
url: "https://ictyangye.github.io"

allowsearch: true

share:
  twitter_username: \#
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
